In [1]:
import tensorflow as tf

# A tensor is an N-Dimensional array of data:

###### Scalar / Real Number

In [2]:
x = tf.constant(3)
print('x = {}'.format(x))

x = Tensor("Const:0", shape=(), dtype=int32)


###### Vector / 1D Tensor

In [3]:
x = tf.constant([3,5,7])
print('x = {}'.format(x))

x = Tensor("Const_1:0", shape=(3,), dtype=int32)


###### Matrix / 2D Tensor

In [4]:
x = tf.constant([
    [3,5,7],
    [4,6,8]
])
print('x = {}'.format(x))

x = Tensor("Const_2:0", shape=(2, 3), dtype=int32)


######  3D Tensor

In [5]:
x = tf.constant([
   [[3,5,7],[4,6,8]],
   [[1,2,3],[4,5,6]]
])
print('x = {}'.format(x))

x = Tensor("Const_3:0", shape=(2, 2, 3), dtype=int32)


######  nD Tensor

In [12]:
x1 = tf.constant([2,3,4])
print('x1 = {}'.format(x1))

x2 = tf.stack([x1, x1])
print('x2 = {}'.format(x2))

x3 = tf.stack([x2, x2, x2, x2])
print('x3 = {}'.format(x3))

x4 = tf.stack([x3, x3])
print('x4 = {}'.format(x4))

x1 = Tensor("Const_9:0", shape=(3,), dtype=int32)
x2 = Tensor("stack_5:0", shape=(2, 3), dtype=int32)
x3 = Tensor("stack_6:0", shape=(4, 2, 3), dtype=int32)
x4 = Tensor("stack_7:0", shape=(2, 4, 2, 3), dtype=int32)


# Tensor can be sliced:

In [26]:
x = tf.constant([
    [3,5,7],
    [4,6,8]
])

sliced_x = x[:, 1]
# Above clone(:) means take all the row and 1 means take column one. As python is zero based
# index, so 1 means columns 2. So we will get second columns all the rows.

sliced_x2 = x[1, :]
# Above 1 means, take the second row and the colone means, take all of the column. That means
# we will end up taking all of the columns of second row

sliced_x3 = x[1, 0:2]
# As usual 1 means take the second row and 0:2 means start from zero but take upto but not including
# index 2, that means we will take column 1 & 2 of the second row.

In [27]:
with tf.Session() as sess:
    print('x = {}'.format(x.eval()))
    print('sliced_x = {}'.format(sliced_x.eval()))
    print('sliced_x2 = {}'.format(sliced_x2.eval()))
    print('sliced_x3 = {}'.format(sliced_x3.eval()))

x = [[3 5 7]
 [4 6 8]]
sliced_x = [5 6]
sliced_x2 = [4 6 8]
sliced_x3 = [4 6]


# Tensor can be reshaped:

###### Example: 1

In [31]:
x = tf.constant([
    [3,5,7],
    [4,6,8]
], name='x')
print('x = {}'.format(x))

reshaped_x = tf.reshape(x, [3,2],name='reshaped_x')
print('reshaped_x = {}'.format(reshaped_x))

x = Tensor("x:0", shape=(2, 3), dtype=int32)
reshaped_x = Tensor("reshaped_x:0", shape=(3, 2), dtype=int32)


In [32]:
with tf.Session() as sess:
    print('x = {}'.format(x.eval()))
    print('reshaped_x = {}'.format(reshaped_x.eval()))

x = [[3 5 7]
 [4 6 8]]
reshaped_x = [[3 5]
 [7 4]
 [6 8]]


###### Example: 2 (Reshape and Slice)

In [34]:
x = tf.constant([
    [3,5,7],
    [4,6,8]
], name='x')
print('x = {}'.format(x))

reshaped_and_sliced_x = tf.reshape(x, [3,2],name='reshaped_and_sliced_x')[1,:]
print('reshaped_and_sliced_x = {}'.format(reshaped_and_sliced_x))

x = Tensor("x_2:0", shape=(2, 3), dtype=int32)
reshaped_and_sliced_x = Tensor("strided_slice_9:0", shape=(2,), dtype=int32)


In [35]:
with tf.Session() as sess:
    print('x = {}'.format(x.eval()))
    print('reshaped_and_sliced_x = {}'.format(reshaped_and_sliced_x.eval()))

x = [[3 5 7]
 [4 6 8]]
reshaped_and_sliced_x = [7 4]
